title: Curriculum Vitae
email: "vita@epidro.me"
description: > 
  Konstantinos Chorianopoulos Curriculum Vitae
baseurl: ""
github_username: epidrome 

# Build settings
#
# minima dependencies quiet sass
sass:
  quiet_deps: true
  silence_deprecations: [import]

theme: "minima"

plugins:
  - jekyll-feed

header_pages:
 - README.md
