title: Curriculum Vitae
author: 
  name: Konstantinos Chorianopoulos
  email: "vita@epidro.me"
description: > 
  Konstantinos Chorianopoulos Curriculum Vitae
baseurl: ""

minima:
  social_links:
    - title: epidrome profile at Github
      icon: github
      url: "https://github.com/epidrome"

# Build settings
#
# minima dependencies quiet sass
sass:
  quiet_deps: true
  silence_deprecations: [import]

remote_theme: "jekyll/minima@495703c"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

header_pages:
 - README.md
